name: Actualizar Pokédex Colectiva

on:
  schedule:
    - cron: '0 2 * * 1' # Todos los lunes a las 02:00 AM
  workflow_dispatch: # Para darle al botón manual

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Ejecutar Generador Colectivo
        run: python generador_colectivo.py
        
      - name: Subir cambios a GitHub
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add collective_*.json
          git commit -m "Actualizacion semanal de Rangos Colectivos y Hall of Fame" || echo "No hay cambios nuevos"
          git push