name: Actualizar Pokédex WCA

on:
  schedule:
    - cron: '0 3 * * 1,2,5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  actualizar-rankings:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clonar repositorio
        uses: actions/checkout@v3

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Descargar base de datos WCA
        run: |
          EXPORT_URL=$(curl -s https://www.worldcubeassociation.org/api/v0/export/public | grep -o '"tsv_url":"[^"]*"' | cut -d'"' -f4)
          wget -O WCA_export.tsv.zip "$EXPORT_URL"
          unzip WCA_export.tsv.zip

      - name: 4. Ejecutar script de Python
        run: python calculadora_rangos_mundial_wca.py

      - name: 5. Guardar los nuevos rankings en GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ranking_*.txt
          git commit -m "Actualización automática de rankings WCA [skip ci]" || echo "No hay cambios nuevos que guardar"
          git push
