name: Actualizar Pokédex WCA

on:
  schedule:
    - cron: '0 3 * * 4' 
  workflow_dispatch:

jobs:
  generar-y-desplegar:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clonar mi código
        uses: actions/checkout@v3

      - name: 2. Preparar entorno Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Descargar última Base de Datos oficial de la WCA
        run: |
          EXPORT_URL=$(curl -s https://www.worldcubeassociation.org/api/v0/export/public | jq -r '.tsv_url')
          wget -O WCA_export.tsv.zip "$EXPORT_URL"
          unzip WCA_export.tsv.zip

      - name: 4. Ejecutar mi script de Python
        run: python calculadora_rangos_wca_todos.py

      - name: 5. Subir la web actualizada a Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: '.'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
